# Generated by Django 4.1.1 on 2022-10-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='SomethingElse',
        ),
    ]
